### ISSUE TITLE
Temperature reading not adjusting to temperature change

### ISSUE THREAD

**Issue by mike-gruendler** [MelvinRook/node-red-contrib-pi-max31865#3]
Hi there!

Thanks a lot for creating the Node!
It would be just the perfect thing for me if it would show the right temperature.

Unfortunately it only shows a reading of -242.02. (important note here that it is the same temp as a friend of mine worked out and got stuck with doing it via a python program and also was this temperature mentioned in another Issue-Discussion on this Node)

I also tried holding the PT100 into 100 degrees water which also didn't change the value at all. 

I have a RaspberryPi 3b+ with a MAX31865 with a PT100 attached. 
The Node is configured as follows: 0,0,100,430,3,CustomName
Jumpers on the MAX31865 are set as on the Picture.
![IMG_2544](https://user-images.githubusercontent.com/11996207/115452853-3e6dc800-a21f-11eb-92bd-6b8a15921381.jpg)

Thanks a lot in advance for helping me out if you got the time!

**Comment by MelvinRook** [comment]
Hey there,

A reading of -242.02 sounds like there is a reading, but CS going wrong, or a configuration error in the board settings (resistance or wires).

Let's figure out what's happening. Could you please take the following steps:

1. Regarding the wiring, let's start with connecting board CS to Pi SPI0 CE0 (BCM 8): https://pinout.xyz/pinout/pin24_gpio8 -- I am assuming the remaining wiring is correct already.
2. `ls -l /dev/spidev*` should give you an indication of the bus digits. With a single board there should be only one device listed.
3. Create a workflow in Node-RED with an input trigger connected to the MAX31865 and a debug output to see if anything happens when you trigger.

Otherwise we should setup a screen sharing call, so I can look with you.

**Comment by mike-gruendler** [comment]
Thank you very much! Unfortunately the thing just started running. I was about to swap the MAX out when it started working properly. As far as I remember I did not do anything besides a couple restarts. I have it now running in 2 wire config. Hopefully this thread helps someone reading it. Thanks for your time and have a great day!

**Comment by job1234** [comment]
I'm having the same problem and can't get it fixed.. My PT100 has 2 wire's.

With "ls -l /dev/spidev*" my output is:
crw-rw---- 1 root spi 153, 0 Mar 24 15:01 /dev/spidev0.0
crw-rw---- 1 root spi 153, 1 Mar 24 15:01 /dev/spidev0.1
